// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llbvmnttrjrxvjenjbmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsYnZtbnR0cmpyeHZqZW5qYm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTk5NjAsImV4cCI6MjA3MjY5NTk2MH0.hGPpGV9_2sXoMvx-7D18-D2GiIxvlGLt2VpY_mcmrQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});